SUPABASE_URL="https://vnlorqqsdyuaaksiexfb.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZubG9ycXFzZHl1YWFrc2lleGZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkwODM2NDIsImV4cCI6MjA5NDY1OTY0Mn0.sfaBW-rszYkIZ1dgh3bemzwJuD0R2lfyMjIsdbARej4"
